#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
rm /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
sed -i '/^}/d' /etc/nginx/sites-available/default
chown -R ubuntu /var/www
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
