#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
rm /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
sed -i '/^}/d' /etc/nginx/sites-available/default
cat <<EOF >/etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location / {
        Content-Type text/html;
        Content-Length 13;
        return 200 "Hello World!";
    }
}
EOF
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx -s reload
