#!/usr/bin/env bash

# Script that configures a new Ubuntu machine to respect above requirements

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a simple index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Configure redirection
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.koketsodev.tech;\n\t}' /etc/nginx/sites-enabled/default

# Reload Nginx configuration
sudo nginx -s reload
