#!/usr/bin/env bash
# Script that configures a custom 404 page for Nginx
# Configure custom 404 page
apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
service nginx restart