#!/usr/bin/env bash
# Script that configures a custom 404 page for Nginx
# Configure custom 404 page
sudo apt-get update -y
sudo apt-get install -y nginx

# Create custom 404 page
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
# Restart Nginx to apply the changes
sudo service nginx restart
