#!/usr/bin/env bash
# configure custom http headers
# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Retrieve the hostname
hostname=$(hostname)

# Add configuration to include custom HTTP header
sudo bash -c 'cat > /etc/nginx/sites-available/default' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $hostname;
    }
}
EOF

# Reload Nginx to apply changes
sudo nginx -s reload
