#!/usr/bin/env bash

# Disable firewall on port 80
sudo ufw allow 80

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' << EOF
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.167.181.61:80 check
    server web-02 54.227.197.16:80 check
EOF

# Enable HAProxy init script
sudo systemctl enable haproxy

# Start HAProxy service
sudo systemctl start haproxy
