#!/usr/bin/env bash
# Install and configure load balancer !
# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' << EOF
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.167.181.61:80 check
    server web-02 54.227.197.16:80 check
EOF

# Add ENABLED=1 to /etc/default/haproxy if it doesn't exist
if ! grep -qxF 'ENABLED=1' /etc/default/haproxy; then
    echo "ENABLED=1" >> /etc/default/haproxy
fi

# Enable and start HAProxy service
sudo systemctl enable haproxy

# Disable firewall and start service
sudo ufw allow 80/tcp
sudo systemctl restart haproxy
