#!/usr/bin/env bash
# debugging nginx port 80
# Delete the existing /sites-enabled/default and replaces it with a copy of
# /sites-available/default. You do that by creating a symbolic link. 
# The flag -s creates a symbolic link, -f deletes the existing file and replaces it

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

conflicting_service=$(sudo netstat -tuln | grep ":80 ")
if [ -n "$conflicting_service" ]; then
    sudo systemctl stop $(echo "$conflicting_service" | awk '{print $7}' | cut -d'/' -f1)
fi

sudo systemctl restart nginx
