#!/usr/bin/env bash
# Will count from 1 - 20 and print bad luck in specific cases

x=1
while [ $x -le 20 ]
do
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)	echo "bad luck from Japan"
			;;
		17)	echo "bad luck from Italy"
			;;
		*)	echo $x
	esac
	((x++));
done
