#!/usr/bin/env bash
# information school file

NAMEF="school"
if [ -e "$NAMEF" ]
then
	echo "$NAMEF file exists"
	if [ -s "$NAMEF" ]
	then
		echo "$NAMEF file is not empty"
	else
		echo "$NAMEF file is empty"
	fi
	if [ -f "$NAMEF" ]
	then
		echo "$NAMEF file is a regular file"
	fi
else
	echo "$NAMEF file does not exist"
fi
