#!/usr/bin/env bash
# A Bash script that accepts one argument
# The script run the 'whoami' command under the user passed as an argument

if [ $# -ne 1 ]; then
    exit 1
fi

if id "$1" &>/dev/null; then
    if [ ! -d "/home/$1" ]; then
        # Run whoami under the specified user
        sudo -u "$1" whoami
    fi
fi
