#!/usr/bin/env bash
# A Bash script that accepts one argument
# The script run the 'whoami' command under the user passed as an argument

# Check if an argument is provided
if id -u "$1" &>/dev/null && [ ! -d "/home/$1" ]; then
    echo "$1"
else
    echo "$1"
fi